### ISSUE TITLE
Exception handling in the `decodeURI` function is required.

### ISSUE THREAD

**Issue by min9nim** [lukejacksonn/servor#85]
error occurred and server is killed.

```
/usr/local/lib/node_modules/http-server-spa/server.js:76
    const resource = path.join(cwd, root, decodeURI(uri));
                                          ^

URIError: URI malformed
    at decodeURI (<anonymous>)
    at Server.<anonymous> (/usr/local/lib/node_modules/http-server-spa/server.js:76:43)
    at Server.emit (node:events:513:28)
    at parserOnIncoming (node:_http_server:1091:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
```

**Comment by nurpax** [comment]
Yep.  I hit this too but in a slightly different code path.

```
/usr/src/app/node_modules/servor/servor.js:145
    const pathname = decodeURI(url.parse(req.url).pathname);
                     ^
URIError: URI malformed
    at decodeURI (<anonymous>)
    at Server.<anonymous> (/usr/src/app/node_modules/servor/servor.js:145:22)
    at Server.emit (node:events:517:28)
    at parserOnIncoming (node:_http_server:1130:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
```
